[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "autordf2gml"
version = "0.0.1"
authors = [
  { name="Michael Faerber", email="michael.faerber@tu-dresden.de" },
  { name="David Lamprecht", email="lamprecht.david@web.de" },
  { name="Yuni Susanti", email="yuni.susanti@mailbox.tu-dresden.de" },
]
description = "AutoRDF2GML: A Framework for Transforming RDF Data into Graph Representations for Graph Machine Learning."
readme = "README.md"
license = {text = "MIT License"}
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Programming Language :: Python :: 3.8",
  "License :: OSI Approved :: MIT License",
]
keywords = ["rdf", "graph dataset", "knowledge graph", "autordf2gml", "gml", "gnn"]
requires-python = ">=3.8,<=3.9.9"
dependencies = [
  'rdflib ~= 6.3.2',
  'pandas ~= 1.3.5',
  'numpy ~= 1.22.4',
  'configparser ~= 6.0.0',
  'scikit-learn ~= 1.1.1',
  'torch ~= 1.12.0',
  'transformers ~= 4.30.2',
  'tqdm ~= 4.65.0',
  'torch-geometric ~= 2.3.0',
  'urllib3 ~= 1.26.6',
]

[project.urls]
Homepage = "https://github.com/davidlamprecht/AutoRDF2GML"
Issues = "https://github.com/davidlamprecht/AutoRDF2GML/issues"